#!/usr/bin/env sh

# Type checking
echo "🔍 Running type check..."
npm run typecheck || exit 1

# Linting
echo "🧹 Running linter..."
npx lint-staged || exit 1

# Format check
echo "💅 Checking code formatting..."
npm run format:check || exit 1

# Tests
echo "🧪 Running tests..."
npm test || exit 1

echo "✅ All checks passed!"
